title: Matt Pro Analytics Blog
description: >-
  Detailed posts on how AI & Analytics can help companies make data-driven decisions.
author: Matt Protopapas
email: matt@kedrosanalytics.com
url: "https://mattprotopapas.github.io"
baseurl: ""

markdown: kramdown
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
